### ISSUE TITLE
[Feature] 채팅방 기능 REST API 구현

### ISSUE THREAD

**Issue by kimday0326** [khu-compath/server#3]
# 🤖 기능 개요

채팅방과 관련된 REST API 를 구현합니다.

## ✅ Todo
- [ ] 채팅방 생성
- [ ] 채팅방 참여
- [ ] 채팅방 목록 가져오기
- [ ] Polling 용 api 작성
- [ ] 이메일 504 에러 해결
